Repository CaZaIt/CaZaIt-Android, pull requests merged in 2023-02, with the labels that each got.

#59 [Refactor] #58 - layout values
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeMenuFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/interest/CafeInterestFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/login/LoginActivity.kt
  app/src/main/res/layout/item_cafe_info_menu.xml
  app/src/main/res/values/dimens.xml
Labels: in progress

#63 [Feat] #60 - cafe information image slide
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/CafeInformationActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeRatingReviewFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/ImageSlideFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/CafeInfoImgViewModel.kt
  app/src/main/res/layout/activity_cafe_information.xml
  app/src/main/res/layout/fragment_image_slide.xml
  app/src/main/res/values/strings.xml
Labels: in progress

#67 [Chore] #66 - 간단한 코드 정리 및 변수명 수정
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/CafeInformationActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeLocTransFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeRatingReviewEditActivity.kt
Labels: in progress

#72 [Feat] #71 - Swipe Refresh
  app/build.gradle
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeMenuFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeRatingReviewFragment.kt
  app/src/main/res/layout/fragment_cafe_menu.xml
  app/src/main/res/layout/fragment_cafe_rating_review.xml
  build.gradle
Labels: complete, review required

#76 [Refactor] #75 - signup activity nickname
  app/src/main/java/org/cazait/cazait_android/SignUpViewModel.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/signup/SignUpActivity.kt
  app/src/main/res/layout/item_cafe_interest.xml
Labels: complete, review required

#84 [Feat] #82 - Login Request & Response
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cazait/cazait_android/data/api/UserService.kt
  app/src/main/java/org/cazait/cazait_android/data/dto/User.kt
  app/src/main/java/org/cazait/cazait_android/data/error/Error.kt
  app/src/main/java/org/cazait/cazait_android/data/error/mapper/ErrorMapper.kt
  app/src/main/java/org/cazait/cazait_android/data/model/User.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/ServiceGenerator.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/datasource/UserRemoteData.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/datasource/UserRemoteDataSource.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/request/LoginRequest.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/response/LoginResponse.kt
  app/src/main/java/org/cazait/cazait_android/data/repository/DataRepository.kt
  app/src/main/java/org/cazait/cazait_android/data/repository/DataRepositoryImpl.kt
  app/src/main/java/org/cazait/cazait_android/network/Network.kt
  app/src/main/java/org/cazait/cazait_android/network/NetworkConnectivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/base/BaseViewModel.kt
  app/src/main/java/org/cazait/cazait_android/ui/util/SingleEvent.kt
  app/src/main/java/org/cazait/cazait_android/ui/util/extension/ArchComponentExt.kt
  app/src/main/java/org/cazait/cazait_android/ui/util/extension/ViewExt.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/login/LoginActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/LoginViewModel.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: refactor, review required

#89 [Refact] #79 - Simple Code Refact
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/CafeInformationActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeLocTransFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/OnMapTouchListener.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/util/OnMapTouchListener.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/util/TouchableWrapper.kt
Labels: complete

#91 [Fix] SplashScreen
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cazait/cazait_android/ui/view/login/LoginActivity.kt
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/themes.xml
Labels: bug

#93 [Feat] #92 - Auto Login
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cazait/cazait_android/Constants.kt
  app/src/main/java/org/cazait/cazait_android/data/model/local/UserPreferences.kt
  app/src/main/java/org/cazait/cazait_android/data/repository/UserRepository.kt
  app/src/main/java/org/cazait/cazait_android/data/repository/UserRepositoryImpl.kt
  app/src/main/java/org/cazait/cazait_android/di/AppModule.kt
  app/src/main/java/org/cazait/cazait_android/di/DataModule.kt
  app/src/main/java/org/cazait/cazait_android/ui/adapter/CafeListItemAdapter.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/login/LoginActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/LoginViewModel.kt
Labels: complete

#95 [Feat] #94 dot indicator
  app/build.gradle
  app/src/main/java/org/cazait/cazait_android/data/Datasource.kt
  app/src/main/java/org/cazait/cazait_android/data/model/CafeImg.kt
  app/src/main/java/org/cazait/cazait_android/ui/adapter/CafeImgAdapter.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/CafeInformationActivity.kt
  app/src/main/res/drawable/image_cafe_ex2.png
  app/src/main/res/layout/activity_cafe_information.xml
  app/src/main/res/layout/item_cafe_img.xml
Labels: in progress, complete

#97 [Feat] #96 image load
  app/src/main/java/org/cazait/cazait_android/data/Datasource.kt
  app/src/main/java/org/cazait/cazait_android/data/model/CafeImg.kt
  app/src/main/java/org/cazait/cazait_android/ui/adapter/CafeImgAdapter.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/CafeInformationActivity.kt
  app/src/main/res/drawable/cafe_menu_americano.png
  app/src/main/res/layout/item_cafe_info_menu.xml
Labels: complete

#100 [Feat] #99 - sign up req, res
  app/src/main/java/org/cazait/cazait_android/data/Datasource.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/datasource/UserRemoteData.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/datasource/UserRemoteDataSource.kt
  app/src/main/java/org/cazait/cazait_android/data/repository/UserRepositoryImpl.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/login/LoginActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/signup/SignUpActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/LoginViewModel.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/SignUpViewModel.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_sign_up.xml
Labels: enhancement, complete, refactor

#103 [Fix] #101 - CafeList Update
  app/src/main/java/org/cazait/cazait_android/data/api/CafeService.kt
  app/src/main/java/org/cazait/cazait_android/data/api/UserService.kt
  app/src/main/java/org/cazait/cazait_android/data/dto/cafe/CafeMenu.kt
  app/src/main/java/org/cazait/cazait_android/data/error/Error.kt
  app/src/main/java/org/cazait/cazait_android/data/error/mapper/ErrorMapper.kt
  app/src/main/java/org/cazait/cazait_android/data/model/Cafe.kt
  app/src/main/java/org/cazait/cazait_android/data/model/CafeImageRes.kt
  app/src/main/java/org/cazait/cazait_android/data/model/local/LocalData.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/ServiceGenerator.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/datasource/UserRemoteData.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/datasource/UserRemoteDataSource.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/request/CafeListRequest.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/response/CafeListResponse.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/response/TokenResponse.kt
  app/src/main/java/org/cazait/cazait_android/data/repository/DataRepositoryImpl.kt
  app/src/main/java/org/cazait/cazait_android/data/repository/UserRepository.kt
  app/src/main/java/org/cazait/cazait_android/data/repository/UserRepositoryImpl.kt
  app/src/main/java/org/cazait/cazait_android/ui/adapter/CafesViewHolder.kt
  app/src/main/java/org/cazait/cazait_android/ui/adapter/MyAdapter.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/CafeListFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/CafeListViewModel.kt
  app/src/main/res/layout/item_cafe_main.xml
  app/src/main/res/values/strings.xml
Labels: complete, refactor, review required

#114 [Feat] #90 menus in cafe
  app/src/main/java/org/cazait/cazait_android/data/api/CafeService.kt
  app/src/main/java/org/cazait/cazait_android/data/api/UserService.kt
  app/src/main/java/org/cazait/cazait_android/data/model/CafeMenu.kt
  app/src/main/java/org/cazait/cazait_android/data/model/CafeMenus.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/datasource/CafeInfoRemoteData.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/datasource/CafeInfoRemoteDataSource.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/datasource/UserRemoteData.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/request/MenuRequest.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/request/ReviewRequest.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/response/MenuResponse.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/response/ReviewResponse.kt
  app/src/main/java/org/cazait/cazait_android/data/repository/DataRepository.kt
  app/src/main/java/org/cazait/cazait_android/data/repository/DataRepositoryImpl.kt
  app/src/main/java/org/cazait/cazait_android/ui/adapter/CafeInfoMenuAdapter.kt
  app/src/main/java/org/cazait/cazait_android/ui/adapter/MenusViewHolder.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/CafeInformationActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeMenuFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/CafeInfoMenuViewModel.kt
  app/src/main/res/layout/fragment_cafe_menu.xml
  app/src/main/res/layout/item_cafe_info_menu.xml
Labels: in progress

#120 [Feat] #115 CafeMenu, CafeLocation Server Network
  app/build.gradle
  app/src/main/java/org/cazait/cazait_android/ui/adapter/CafeImgAdapter.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/CafeListFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/CafeInformationActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeLocTransFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeMenuFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/CafeInfoLocTransViewModel.kt
Labels: in progress

#123 [Refact] #122 - 불필요한 부분
  app/src/main/java/org/cazait/cazait_android/data/Datasource.kt
  app/src/main/java/org/cazait/cazait_android/ui/adapter/CafeInfoMenuAdapter.kt
  app/src/main/java/org/cazait/cazait_android/ui/adapter/holder/MenusViewHolder.kt
Labels: complete

#129 [Feat] #124 cafe menu image
  app/src/main/java/org/cazait/cazait_android/data/model/CafeMenu.kt
  app/src/main/java/org/cazait/cazait_android/ui/adapter/CafeInfoMenuAdapter.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeMenuFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/CafeInfoMenuViewModel.kt
Labels: complete

#130 [Feat] #106 cafe info rating reivew
  app/src/main/java/org/cazait/cazait_android/data/api/CafeService.kt
  app/src/main/java/org/cazait/cazait_android/data/model/ReviewData.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/datasource/CafeInfoRemoteData.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/datasource/CafeInfoRemoteDataSource.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/request/ReviewEditRequest.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/response/ReviewEditResponse.kt
  app/src/main/java/org/cazait/cazait_android/data/repository/DataRepository.kt
  app/src/main/java/org/cazait/cazait_android/data/repository/DataRepositoryImpl.kt
  app/src/main/java/org/cazait/cazait_android/ui/adapter/CafeInfoReviewAdapter.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/CafeInformationActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeRatingReviewEditActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeRatingReviewFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/login/LoginActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/CafeInfoLocTransViewModel.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/CafeInfoReviewEditViewModel.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/CafeInfoViewModel.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/LoginViewModel.kt
  app/src/main/res/layout/activity_cafe_rating_review_edit.xml
  app/src/main/res/layout/item_cafe_info_rating_review.xml
Labels: in progress

#140 [Fix] #133 - LoginActivity Errors (context), AppModule
  app/src/main/java/org/cazait/cazait_android/di/AppModule.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/login/LoginActivity.kt
Labels: bug, refactor, review required

#141 [Refact] #132 - cafeinforatingreview viewmodel
  app/src/main/java/org/cazait/cazait_android/data/model/remote/response/MenuResponse.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/response/ReviewResponse.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/CafeInformationActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeRatingReviewFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/CafeInfoReviewViewModel.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/CafeInfoViewModel.kt
Labels: in progress

#143 [Feat] #142 - non review data
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeRatingReviewFragment.kt
  app/src/main/res/layout/fragment_cafe_rating_review.xml
  app/src/main/res/values/strings.xml
Labels: in progress
