Repository CaZaIt/CaZaIt-Android, pull requests merged in 2023-01, with the labels that each got.

#1 [Add] inital settings - gradle, directory, package
  .idea/vcs.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cazait/cazait_android/CaZaItApplication.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
  build.gradle
  docs/README.md
Labels: good first issue

#5 [Add] #2 Login Activity
  .idea/gradle.xml
  app/build.gradle
  app/src/debug/ic_kazait-playstore.png
  app/src/debug/ic_launcher-playstore.png
  app/src/debug/res/mipmap-anydpi-v26/ic_kazait.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_kazait_round.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/debug/res/mipmap-hdpi/ic_kazait.png
  app/src/debug/res/mipmap-hdpi/ic_kazait_foreground.png
  app/src/debug/res/mipmap-hdpi/ic_kazait_round.png
  app/src/debug/res/mipmap-hdpi/ic_launcher.png
  app/src/debug/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-hdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-mdpi/ic_kazait.png
  app/src/debug/res/mipmap-mdpi/ic_kazait_foreground.png
  app/src/debug/res/mipmap-mdpi/ic_kazait_round.png
  app/src/debug/res/mipmap-mdpi/ic_launcher.png
  app/src/debug/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-mdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xhdpi/ic_kazait.png
  app/src/debug/res/mipmap-xhdpi/ic_kazait_foreground.png
  app/src/debug/res/mipmap-xhdpi/ic_kazait_round.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xxhdpi/ic_kazait.png
  app/src/debug/res/mipmap-xxhdpi/ic_kazait_foreground.png
  app/src/debug/res/mipmap-xxhdpi/ic_kazait_round.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xxxhdpi/ic_kazait.png
  app/src/debug/res/mipmap-xxxhdpi/ic_kazait_foreground.png
  app/src/debug/res/mipmap-xxxhdpi/ic_kazait_round.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/debug/res/values/ic_kazait_background.xml
  app/src/debug/res/values/ic_launcher_background.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cazait/cazait_android/ui/view/login/LoginActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/signup/SignupActivity.kt
  app/src/main/res/drawable-v24/arrow_back.png
  app/src/main/res/drawable-v24/logo.png
  app/src/main/res/drawable/round_white_rectangle.xml
  app/src/main/res/drawable/round_wood_rectangle.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: good first issue

#6 [Add] #3 - RecyclerView in Fragment with Viewmodel
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cazait/cazait_android/ui/view/PracticeActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/CafeListFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/CafeListRVAdapter.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/ViewModel.kt
  app/src/main/res/drawable-hdpi/favorite.9.png
  app/src/main/res/drawable-mdpi/favorite.9.png
  app/src/main/res/drawable-xhdpi/favorite.9.png
  app/src/main/res/drawable-xxhdpi/favorite.9.png
  app/src/main/res/drawable-xxxhdpi/favorite.9.png
  app/src/main/res/drawable/favorite.png
  app/src/main/res/drawable/ic_baseline_dashboard_24.xml
  app/src/main/res/drawable/ic_baseline_home_24.xml
  app/src/main/res/drawable/ic_baseline_notifications_24.xml
  app/src/main/res/drawable/imgcafe2.png
  app/src/main/res/drawable/outline.xml
  app/src/main/res/drawable/roundcorner.xml
  app/src/main/res/layout/activity_practice.xml
  app/src/main/res/layout/cafe_item_data.xml
  app/src/main/res/layout/fragment_cafe_list.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: good first issue

#7 [Add] #4 - Cafe Information Activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/CafeInformationActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeMenuFragment.kt
  app/src/main/res/drawable/ex_cafe_landscape.png
  app/src/main/res/drawable/img.png
  app/src/main/res/drawable/img_non_selected.png
  app/src/main/res/drawable/img_selected.png
  app/src/main/res/drawable/selector_cafe_info.xml
  app/src/main/res/layout/activity_cafe_information.xml
  app/src/main/res/layout/fragment_cafe_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: good first issue

#14 [Feat] #12 - MainActivity, CafeListFragment, Adapter
  app/src/main/java/org/cazait/cazait_android/ui/view/MainActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/CafeListFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/CafeListRVAdapter.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/CafeInfoViewModel.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/MainViewModel.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/ViewModel.kt
  app/src/main/res/drawable-hdpi/add.9.png
  app/src/main/res/drawable-hdpi/home.9.png
  app/src/main/res/drawable-hdpi/person_filled.9.png
  app/src/main/res/drawable-mdpi/add.9.png
  app/src/main/res/drawable-mdpi/home.9.png
  app/src/main/res/drawable-mdpi/person_filled.9.png
  app/src/main/res/drawable-xhdpi/add.9.png
  app/src/main/res/drawable-xhdpi/home.9.png
  app/src/main/res/drawable-xhdpi/person_filled.9.png
  app/src/main/res/drawable-xxhdpi/add.9.png
  app/src/main/res/drawable-xxhdpi/home.9.png
  app/src/main/res/drawable-xxhdpi/person_filled.9.png
  app/src/main/res/drawable-xxxhdpi/add.9.png
  app/src/main/res/drawable-xxxhdpi/home.9.png
  app/src/main/res/drawable-xxxhdpi/person_filled.9.png
  app/src/main/res/drawable/add.png
  app/src/main/res/drawable/base_ellipse.png
  app/src/main/res/drawable/cazait_icon.png
  app/src/main/res/drawable/filter.png
  app/src/main/res/drawable/home.png
  app/src/main/res/drawable/menu.png
  app/src/main/res/drawable/person_filled.png
  app/src/main/res/drawable/search.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/cafe_item_data.xml
  app/src/main/res/layout/fragment_cafe_list.xml
  app/src/main/res/layout/item_cafe_main.xml
  app/src/main/res/menu/menu_bottom_nav.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
Labels: complete

#16 [Refactor] #10 - 변수명 변경, 에디트텍스트 늘어나는 것 고정, 스플래시 커스텀
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cazait/cazait_android/SplashActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/login/LoginActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/signup/SignupActivity.kt
  app/src/main/res/anim/splash_iv.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: invalid, in progress, refactor, review required

#19 [Add] #17 - MyPageFragment
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/org/cazait/cazait_android/ui/view/mypage/MyPageFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/ViewModel.kt
  app/src/main/res/drawable-hdpi/arrow_front.png
  app/src/main/res/drawable-hdpi/image_my_page_login.png
  app/src/main/res/drawable-v24/ic_coupon.png
  app/src/main/res/drawable/ic_announcement.png
  app/src/main/res/drawable/ic_credit_card.png
  app/src/main/res/drawable/ic_interest_store.png
  app/src/main/res/drawable/ic_service_center.png
  app/src/main/res/drawable/ic_setting.png
  app/src/main/res/drawable/ic_store.png
  app/src/main/res/drawable/ic_terms_policies.png
  app/src/main/res/drawable/round_coffee_rectangle.xml
  app/src/main/res/drawable/round_white_rectangle.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/colors.xml
Labels: complete, review required

#21 [Fix] MainActivity, CafeListFragment: 불안정한 코드, 리소스 수정
  app/src/main/java/org/cazait/cazait_android/ui/util/extension/ViewExtension.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/MainActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/CafeListFragment.kt
  app/src/main/res/color/selector_btn_cafe_info.xml
  app/src/main/res/drawable-hdpi/all_menu_circle.png
  app/src/main/res/drawable/all_filter.png
  app/src/main/res/drawable/all_search.png
  app/src/main/res/drawable/btn_info_confirm.xml
  app/src/main/res/drawable/cazait_icon.png
  app/src/main/res/drawable/filter.png
  app/src/main/res/drawable/ic_cazait_logo.png
  app/src/main/res/drawable/menu.png
  app/src/main/res/drawable/round_coffee_rectangle.xml
  app/src/main/res/drawable/round_white_rectangle.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/fragment_cafe_list.xml
  app/src/main/res/menu/menu_bottom_nav.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: bug, refactor, review required

#27 [Feat] #18 - cafe information page
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cazait/cazait_android/ui/adapter/CafeInfoMenuRVAdapter.kt
  app/src/main/java/org/cazait/cazait_android/ui/adapter/CafeInfoReviewRVAdapter.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/CafeInformationActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeLocTransFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeMenuFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeRatingReviewEdit.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeRatingReviewFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/OnMapTouchListener.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/TouchableWrapper.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/CafeInfoMenuViewModel.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/CafeInfoReviewViewModel.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/CafeInfoViewModel.kt
  app/src/main/res/color/selector_btn_cafe_info.xml
  app/src/main/res/drawable/americano.png
  app/src/main/res/drawable/btn_clicked.xml
  app/src/main/res/drawable/btn_unclicked.xml
  app/src/main/res/drawable/cafe_info_rating_review_edit.png
  app/src/main/res/drawable/cafe_info_rating_review_edit_star_empty.png
  app/src/main/res/drawable/cafe_info_rating_review_edit_star_full.png
  app/src/main/res/drawable/cafe_info_rating_review_filter.png
  app/src/main/res/drawable/cafe_info_rating_review_score_star.png
  app/src/main/res/drawable/cafe_info_rating_review_star_empty.png
  app/src/main/res/drawable/cafe_info_rating_review_star_full.png
  app/src/main/res/drawable/outline.xml
  app/src/main/res/drawable/selector_btn_click.xml
  app/src/main/res/layout/activity_cafe_information.xml
  app/src/main/res/layout/activity_cafe_rating_review_edit.xml
  app/src/main/res/layout/fragment_cafe_loc_trans.xml
  app/src/main/res/layout/fragment_cafe_menu.xml
  app/src/main/res/layout/fragment_cafe_rating_review.xml
  app/src/main/res/layout/item_cafe_info_menu.xml
  app/src/main/res/layout/item_cafe_info_rating_review.xml
  app/src/main/res/menu/menu_cafe_info_rating_review_context_menu.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
  gradle.properties
  settings.gradle
Labels: in progress

#36 [Feat] #28 - cafe information page review edit
  .idea/gradle.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/CafeInformationActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeRatingReviewEdit.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeRatingReviewEditActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeRatingReviewFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/TouchableWrapper.kt
  app/src/main/res/drawable/btn_review_outline.xml
  app/src/main/res/drawable/review_outline.xml
  app/src/main/res/layout/activity_cafe_rating_review_edit.xml
  app/src/main/res/layout/fragment_cafe_loc_trans.xml
  app/src/main/res/values/strings.xml
Labels: in progress

#40 [Feat] #37 - ratingreview frag context menu
  app/src/main/java/org/cazait/cazait_android/data/model/CafeMenu.kt
  app/src/main/java/org/cazait/cazait_android/data/model/CafeRatingReview.kt
  app/src/main/java/org/cazait/cazait_android/data/model/ReviewData.kt
  app/src/main/java/org/cazait/cazait_android/data/model/remote/ServiceGenerator.kt
  app/src/main/java/org/cazait/cazait_android/ui/adapter/CafeInfoMenuAdapter.kt
  app/src/main/java/org/cazait/cazait_android/ui/adapter/CafeInfoMenuRVAdapter.kt
  app/src/main/java/org/cazait/cazait_android/ui/adapter/CafeInfoReviewAdapter.kt
  app/src/main/java/org/cazait/cazait_android/ui/adapter/CafeInfoReviewRVAdapter.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeMenuFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeRatingReviewEditActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeRatingReviewFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/CafeInfoMenuViewModel.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/CafeInfoReviewViewModel.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/CafeInfoViewModel.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/MainViewModel.kt
  app/src/main/res/layout/fragment_cafe_menu.xml
  app/src/main/res/layout/item_cafe_info_menu.xml
  app/src/main/res/layout/item_cafe_info_rating_review.xml
  app/src/main/res/layout/item_cafe_main.xml
  app/src/main/res/values/strings.xml
Labels: in progress

#49 [Refactor] #46 - location access agree
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeLocTransFragment.kt
Labels: in progress

#55 [Refact] #46 - location access agree
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/CafeInformationActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/cafelist/info/inner/CafeRatingReviewEditActivity.kt
  app/src/main/java/org/cazait/cazait_android/ui/view/interest/CafeInterestFragment.kt
  app/src/main/java/org/cazait/cazait_android/ui/viewmodel/CafeInterestViewModel.kt
  app/src/main/res/layout/activity_cafe_information.xml
Labels: in progress
